### ISSUE TITLE
Establish workflow

### ISSUE THREAD

**Issue by Mester** [JessicaNgo/TeleGiphy#1]
We need to agree on a workflow, or there will be lots of clashing

https://github.com/JessicaNgo/TeleGiphy/blob/workflow/workflow.md

**Comment by zapplecat** [comment]
Work flow will be provided in spec on Google doc.

**Comment by Mester** [comment]
I suggest we keep things here instead of some parts on gdocs and some here

**Comment by zapplecat** [comment]
Does github support UMLs?

**Comment by Mester** [comment]
Don't think so, would probably have to be images

**Comment by zapplecat** [comment]
I am fine with the workflow as is. Maybe we'll have standups/check in every other day for progress?

**Comment by corez92** [comment]
Sounds good.
