### ISSUE TITLE
Server receives game token

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#16]
If game token is valid, this will direct player to game lobby. If the token is invalid (either no token exists or game has started), this will give an error.

**Comment by zapplecat** [comment]
`urls` regex might easily take care of this. kwarg might be used for username. See https://docs.djangoproject.com/en/1.10/topics/http/urls/#views-extra-options

**Comment by corez92** [comment]
This will be related to #19 will do it today as well.
