### ISSUE TITLE
Game Start

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#19]
When the game start mechanism is called, it will change the values in the database to disallow any more participants even if they have a valid game token.

**Comment by corez92** [comment]
I'll do this today.

**Comment by Mester** [comment]
Sorry, i was already kinda working on #16 and #19. Didn't realize. Lemme know before you start on it so you don't repeat the work

**Comment by corez92** [comment]
Okay no problem, go ahead. I'll work on username input views for multi then.

**Comment by JessicaNgo** [comment]
@Mester  has made it so participants aren't allowed to join after the game starts. I just PR'd the start_game for multiplayer to change the game to an active state
