### ISSUE TITLE
django Models

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#25]
Models for various aspects of the game. Few are listed below, thought out with standard SQL columns. Add more in comments if necessary.
- [x] Auth (game) tokens: id, token, game_active
- [x] User tokens (paired with auth for active users): id, token
- [x] User: id, username, user token id, auth token id
- [x] Game rounds: id, round #, user id

**Comment by zapplecat** [comment]
Added a few more items to game rounds: user_text, giphy_url, and game_over

**Comment by zapplecat** [comment]
Waiting on resolution on #26 before making pull request.

**Comment by zapplecat** [comment]
Will be redoing these to be more simple, one on one relationships.

**Comment by zapplecat** [comment]
If people have no complaints on the current models structure, someone please merge and delete #30  branch.

**Comment by corez92** [comment]
Yeah, but how does this work? Do people have to fill in their username somewhere? I was thinking we could use sessions to identify unique people OR make like 4-6 basic usernames and people just use those to join a game, but that's the lame way lol

Anyway I think we need to sit down and discuss this model.

I also think there has to be a field called Initial_word that is True/False for the game round table. It checks to see if the entry is the initial one when the game starts.

**Comment by zapplecat** [comment]
I merged the initial model, but we can sit down to talk about this and make edits if necessary.

Re: your questions:
1. Instead of the game immediately giving them their token, the user should type in a screen name. Then they will receive a game token. The reason the user token exists is for a REST API where the client can pass the user and game token and we (the server) will fact check their query.
2. We don't need an initial_word field since we know which round is the first round, and we can just find the initial `GameRounds.user_text` off of that.
