### ISSUE TITLE
Secret Key Empty when available

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#26]
I am getting a `django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.` when I try to run `python manage.py check`

I suspect this is due to the slightly different settings from the default settings.py

**Comment by zapplecat** [comment]
Temporary solve by using settings.py instead of /settings

@Mester Can you take a look at this?

**Comment by Mester** [comment]
The base settings file was actually unchanged from the default settings file, aside from adding 'game' to apps. Did you setup your machine correctly, like I put in the readme? Either `export DJANGO_SETTINGS_MODULE=tele_giphy.settings.local`. I forgot to adjust manage.py, lemme do that

**Comment by Mester** [comment]
Try it now (remember to pull in the changes)

**Comment by zapplecat** [comment]
@Mester No longer getting issues with secret key, but there seems to be a few issues with the directions. I will open another issue for this. This can stay open until we've confirmed everything to be working.

**Comment by zapplecat** [comment]
Issues solved
