### ISSUE TITLE
Flask or Django

### ISSUE THREAD

**Issue by Mester** [JessicaNgo/TeleGiphy#3]
I didn't see any decision on this yet. So what will it be?

**Comment by zapplecat** [comment]
I'm going to say Flask. No need to overcomplicate things before they begin.

**Comment by JessicaNgo** [comment]
django for anarchy

**Comment by JessicaNgo** [comment]
jk lets do flask for simplicity

**Comment by Mester** [comment]
Well django was for the learning experience, but sure we can go with flask

**Comment by corez92** [comment]
I say Flask, I want to be a good at Flask and not meh at Django and Flask.

**Comment by JessicaNgo** [comment]
DJANGO FOR LIFE,  I really think tackling it together will be fun

**Comment by zapplecat** [comment]
OK django.
