### ISSUE TITLE
Hotseat gameplay

### ISSUE THREAD

**Issue by JessicaNgo** [JessicaNgo/TeleGiphy#37]
going to try to make game working for hotseat gameplay wish me lucky guys

**Comment by JessicaNgo** [comment]
Going to sleep now. It's 6:50 am LOL. 

see branch hotseat-gameplay for changes - 

I made html page for the game lobby, it looks like this:
https://gyazo.com/f2b3aacc30672998a5d07be874e5c323

**Comment by JessicaNgo** [comment]
rip me this should have been a milestone

**Comment by JessicaNgo** [comment]
kilometerstone in real units

**Comment by JessicaNgo** [comment]
maybe i should sleep

**Comment by JessicaNgo** [comment]
but i can't because this issue is too big and no one else can work on it unless i pull this thing into master

**Comment by JessicaNgo** [comment]
or else merge errors :-1:

**Comment by Mester** [comment]
what the fuck

**Comment by corez92** [comment]
cant you just push the branch? dont think that should give merge errors?
