### ISSUE TITLE
Game Over

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#40]
Game over views and UI

**Comment by zapplecat** [comment]
Progress!

http://imgur.com/Q7DfQdz

**Comment by corez92** [comment]
This is finished right?

**Comment by zapplecat** [comment]
It is not. Current hotseat method will not work for multiplayer.

**Comment by zapplecat** [comment]
Basically completed. Should I wait until UserGame is populated to make PR? Or should we just merge this for now and edit code once UserGame is actually populated?
