### ISSUE TITLE
Button for hotseat to finish game instead of hardcoded rounds

### ISSUE THREAD

**Issue by Mester** [JessicaNgo/TeleGiphy#45]

**Comment by JessicaNgo** [comment]
i need emotional support

**Comment by JessicaNgo** [comment]
we're all in this together

**Comment by taqpol** [comment]
WHY ARE YOU SO WEIRD

**Comment by corez92** [comment]
Jessica you can do this

**Comment by JessicaNgo** [comment]
just need to add in @Zizibaluba  's gameover stuff. Button is there!

**Comment by zapplecat** [comment]
Will be addressing this in gameplay_enhancement branch I created today.
