### ISSUE TITLE
Pre game over

### ISSUE THREAD

**Issue by Mester** [JessicaNgo/TeleGiphy#65]
Basically the backend processing before the gameover/results screen. Maybe not needed and just do all processing on the final view

**Comment by JessicaNgo** [comment]
do ALL the issues

**Comment by zapplecat** [comment]
I've been planning for this to be in the gameover view. Here are the few things I think we need:
- Remove session/end game
- Remove current game data from db

Anything else? Of course, the above 2 is performed AFTER we load the data we need from the db to memory.

**Comment by zapplecat** [comment]
I've added a crude version of this by simply deleting the game after gameover is displayed. Not sure if the delete is cascading or whether there's leftover data in there...
