### ISSUE TITLE
Clarification on game play

### ISSUE THREAD

**Issue by corez92** [JessicaNgo/TeleGiphy#7]
**Case: 6 people playing Telegiphy**
One player has to initiate a game session. Just like Hangouts, you go to the site and click on a button for a new game. You get a link or (extra feature) send an e-mail invite (or better yet make use of some social media, maybe we can even just use slack to send invites, I think slack would work best since we’ll probably test it out with people from rmotr). You wait until enough people join and the creator has the power to make the game start. When the game starts, the site will:

_TWO OPTIONS:_
1.  You randomly get a word, but then I don’t know what to do next? Because you already have the word so how do you “make a giphy” out of that? Wouldn’t you just type the same word for giphy? Or do you just think of a text to describe the word? And that text you send to giphy to make a new gif? Because my whole gripe is that that person isn’t doing anything, they’re just passing a message along.
2.  The site automatically generates a giphy for you and you have describe it for example. That description creates a new gif and that gif is sent to the next person (order of play is randomly decided). 

The next person will then guess the correct statement that created that gif. You keep on doing that until the last player comes and then that player makes another word guess. The site then compares the two words by the first and last player and see if they are the same, if so: winner winner chicken dinner. If not then well you lose, bitch.

Game summary: each person’s word and the corresponding gif.
We should keep tally maybe of how many times there was a total success and how many times people had mini wins, obviously weighted since the first few persons had more relevant words. But we can brainstorm on this some more.

Gameplay example:

Need to discuss the idea where the two options diverge first.

**PROPOSAL: setup a hangout session tonight 5PM (my time). B&J: that's 2PM for you guys. A: that's 11PM I believe. I'm on East coast time.**

Topic: Discuss gameplay. Discuss specs and goals. etc. We can put up a list of stuff we want to discuss in an agenda.

**Comment by zapplecat** [comment]
Discussed. See #5 #6 for details on implementation.

Game sessions can be asynchronous by enforcing players to use tokens and return "awaiting other players" responses when other players have not performed their "move". This is a similar mechanism as 1st week's tic-tac-toe. The state of the game can be monitored within a collection in MongoDB.
