### ISSUE TITLE
Pass On Button not disabled for multiplayer

### ISSUE THREAD

**Issue by zapplecat** [JessicaNgo/TeleGiphy#95]
Currently the context passes `""` for the `gif` param so the html doesn't detect it's the static image.

**Comment by corez92** [comment]
Started with this [clicky](https://github.com/JessicaNgo/TeleGiphy/tree/pass_on_multi_fix)

I'll look into making it to one condition for the if statement and possibly make it more elegant if at all possible.

**Comment by zapplecat** [comment]
Going to look into this again. Probably isn't a hard fix.
